BLANK_CHARACTER = ' '
INITIAL_STATE = 'InitialState'

YES_FINAL_STATE = 'YES'
NO_FINAL_STATE = 'NO'

FINAL_STATES = [YES_FINAL_STATE, NO_FINAL_STATE]

# Tape pointer direction
FORWARDS = 1
DO_NOT_MOVE = 0
BACKWARDS = -1

VALID_CHARACTERS = { '0', '1', BLANK_CHARACTER }

INVALID_STATE_CHARACTERS = [ '_', '-', ':' ]
